<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Doctor\Catalogs\Exercise;

class ExerciseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $exercises = [
            [
                'name' => 'Sentadillas',
                'exercise_type_id' => 1,
                'intensity' => 'media',
                'duration_minutes' => 10,
                'description' => 'Ejercicio básico para fortalecer piernas.',
                'calories_burned' => 80,
                'sets' => 3,
                'repetitions' => 15,
                'rest_seconds' => 60,
                'equipment' => 'Ninguno',
                'contraindications' => 'Evitar en caso de lesiones de rodilla.',
                'notes' => 'Mantener la espalda recta.',
                'is_active' => true,
            ],
            [
                'name' => 'Flexiones',
                'exercise_type_id' => 1,
                'intensity' => 'alta',
                'duration_minutes' => 8,
                'description' => 'Ejercicio para fortalecer el tren superior.',
                'calories_burned' => 70,
                'sets' => 4,
                'repetitions' => 12,
                'rest_seconds' => 45,
                'equipment' => 'Ninguno',
                'contraindications' => 'Evitar en caso de problemas de hombro.',
                'notes' => 'No bajar demasiado el pecho.',
                'is_active' => true,
            ],
            [
                'name' => 'Caminata',
                'exercise_type_id' => 2,
                'intensity' => 'baja',
                'duration_minutes' => 30,
                'description' => 'Caminata ligera al aire libre.',
                'calories_burned' => 120,
                'sets' => 1,
                'repetitions' => 0,
                'rest_seconds' => 0,
                'equipment' => 'Ninguno',
                'contraindications' => null,
                'notes' => 'Ideal para principiantes.',
                'is_active' => true,
            ],
            [
                'name' => 'Bicicleta estacionaria',
                'exercise_type_id' => 2,
                'intensity' => 'media',
                'duration_minutes' => 20,
                'description' => 'Ejercicio cardiovascular en bicicleta fija.',
                'calories_burned' => 150,
                'sets' => 1,
                'repetitions' => 0,
                'rest_seconds' => 0,
                'equipment' => 'Bicicleta estacionaria',
                'contraindications' => 'Evitar en caso de problemas de rodilla.',
                'notes' => 'Mantener ritmo constante.',
                'is_active' => true,
            ],
            [
                'name' => 'Abdominales',
                'exercise_type_id' => 1,
                'intensity' => 'media',
                'duration_minutes' => 10,
                'description' => 'Abdominales clásicos en el suelo.',
                'calories_burned' => 60,
                'sets' => 3,
                'repetitions' => 20,
                'rest_seconds' => 30,
                'equipment' => 'Ninguno',
                'contraindications' => 'Evitar en caso de dolor lumbar.',
                'notes' => 'No forzar el cuello.',
                'is_active' => true,
            ],
            [
                'name' => 'Plancha',
                'exercise_type_id' => 1,
                'intensity' => 'alta',
                'duration_minutes' => 5,
                'description' => 'Plancha abdominal en el suelo.',
                'calories_burned' => 50,
                'sets' => 3,
                'repetitions' => 1,
                'rest_seconds' => 60,
                'equipment' => 'Ninguno',
                'contraindications' => 'Evitar en caso de problemas de hombro.',
                'notes' => 'Mantener el cuerpo alineado.',
                'is_active' => true,
            ],
            [
                'name' => 'Yoga',
                'exercise_type_id' => 3,
                'intensity' => 'baja',
                'duration_minutes' => 40,
                'description' => 'Rutina básica de yoga para estiramiento.',
                'calories_burned' => 100,
                'sets' => 1,
                'repetitions' => 0,
                'rest_seconds' => 0,
                'equipment' => 'Esterilla',
                'contraindications' => null,
                'notes' => 'Enfocarse en la respiración.',
                'is_active' => true,
            ],
            [
                'name' => 'Natación',
                'exercise_type_id' => 2,
                'intensity' => 'alta',
                'duration_minutes' => 30,
                'description' => 'Nado libre en piscina.',
                'calories_burned' => 250,
                'sets' => 1,
                'repetitions' => 0,
                'rest_seconds' => 0,
                'equipment' => 'Piscina',
                'contraindications' => 'Evitar en caso de infecciones cutáneas.',
                'notes' => 'Mantener hidratación.',
                'is_active' => true,
            ],
            [
                'name' => 'Elíptica',
                'exercise_type_id' => 2,
                'intensity' => 'media',
                'duration_minutes' => 25,
                'description' => 'Ejercicio cardiovascular en elíptica.',
                'calories_burned' => 140,
                'sets' => 1,
                'repetitions' => 0,
                'rest_seconds' => 0,
                'equipment' => 'Máquina elíptica',
                'contraindications' => 'Evitar en caso de dolor articular.',
                'notes' => 'Ajustar resistencia según capacidad.',
                'is_active' => true,
            ],
            [
                'name' => 'Zancadas',
                'exercise_type_id' => 1,
                'intensity' => 'media',
                'duration_minutes' => 10,
                'description' => 'Zancadas alternas con peso corporal.',
                'calories_burned' => 75,
                'sets' => 3,
                'repetitions' => 12,
                'rest_seconds' => 45,
                'equipment' => 'Ninguno',
                'contraindications' => 'Evitar en caso de lesiones de rodilla.',
                'notes' => 'Rodilla no debe sobrepasar la punta del pie.',
                'is_active' => true,
            ],
        ];

        foreach ($exercises as $exercise) {
            Exercise::create($exercise);
        }
    }
}
